networks:
    expressnetwork:

services:
    expressjs:
        build: ./expressjs
        networks:
            - expressnetwork
        deploy:
            mode: replicated
            replicas: 2
    nginx:
        build: ./nginx
        depends_on:
            - expressjs
        networks:
            - expressnetwork
        ports:
            - '80:80'
